name: Auto merge main to heroku-deploy

on:
  push:
    branches:
      - main

jobs:
  merge-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-all: true
          ref: main

      - name: Merge main into heroku-deploy
        run: |
          git config --global user.email "idk@users.noreply.github.com"
          git config --global user.name "No Name"
          git branch
          git checkout heroku-deploy
          git merge --no-commit main
          git push origin heroku-deploy
